### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by ghost** [barenddt/paladins-api-node#2]
{ Error: connect ECONNREFUSED 127.0.0.1:80
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80 }

**Comment by barenddt** [comment]
Documentation has been updated. Please have a look.
